### ISSUE TITLE
Error preventing update

### ISSUE THREAD

**Issue by Dragnucs** [popeye123/ytcc#3]
Updating returns the following:

```bash
$ ytcc
Updating channels...
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/lib/python3.5/site-packages/ytcc-1.5.1-py3.5.egg/ytcc/core.py", line 205, in _update_channel
    feed = feedparser.parse("https://www.youtube.com/feeds/videos.xml?channel_id=" + yt_channel_id)
  File "/usr/lib/python3.5/site-packages/feedparser.py", line 3957, in parse
    saxparser.parse(source)
  File "/usr/lib64/python3.5/site-packages/drv_libxml2.py", line 189, in parse
    eltName = (_d(reader.NamespaceUri()),\
  File "/usr/lib64/python3.5/site-packages/drv_libxml2.py", line 70, in _d
    return _decoder(s)[0]
  File "/usr/lib64/python3.5/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
TypeError: a bytes-like object is required, not 'str'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/ytcc", line 4, in <module>
    __import__('pkg_resources').run_script('ytcc==1.5.1', 'ytcc')
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1657, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.5/site-packages/ytcc-1.5.1-py3.5.egg/EGG-INFO/scripts/ytcc", line 4, in <module>
    __import__('pkg_resources').run_script('ytcc==1.5.1', 'ytcc')
  File "/usr/lib/python3.5/site-packages/ytcc-1.5.1-py3.5.egg/ytcc/cli.py", line 510, in main
  File "/usr/lib/python3.5/site-packages/ytcc-1.5.1-py3.5.egg/ytcc/cli.py", line 493, in parse_args
  File "/usr/lib/python3.5/site-packages/ytcc-1.5.1-py3.5.egg/ytcc/cli.py", line 40, in update_all
  File "/usr/lib/python3.5/site-packages/ytcc-1.5.1-py3.5.egg/ytcc/core.py", line 221, in update_all
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
TypeError: a bytes-like object is required, not 'str'
```

**Comment by popeye123** [comment]
I will investigate this issue, when I have some spare time. My first guess is that libxml2 was updated on your system. I remember that an update of libxml2 caused a similar issue for me a few months ago. What is the version of libxml2 and the distro you use?

**Comment by Dragnucs** [comment]
I use Fedora with the repository Updates and everything updated. Can this be a SELinux related?

On November 22, 2016 8:13:23 PM GMT+00:00, Wolfgang Popp <notifications@github.com> wrote:
>I will investigate this issue, when I have some spare time. My first
>guess is that libxml2 was updated on your system. I remember that an
>update of libxml2 caused a similar issue for me a few months ago. What
>is the version of libxml2 and the distro you use? 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/popeye123/ytcc/issues/3#issuecomment-262352646

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by popeye123** [comment]
No, this problem is not SELinux related. I was able to reproduce this issue on Fedora 25 and it is indeed a bug in libxml2 and its Python bindings. The bug was fixed in libxml2 version 2.9.4 but Fedora 25 still uses version 2.9.3. 

I submitted a [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1398939) to Fedora's bug tracker.

For now you can workaround this issue by installing and using ytcc in a Python virtual environment:
```bash
# Setup the virtualenv and install ytcc
sudo dnf install redhat-rpm-config libxml2-devel libxslt-devel python3-virtualenvwrapper
export VIRTUALENVWRAPPER_VIRTUALENV=/usr/bin/virtualenv-3
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
source /usr/bin/virtualenvwrapper.sh
mkvirtualenv ytcc
./setup.py install

# Leave the virtualenv
deactivate

# 'Resume' the virtualenv
workon ytcc
```

**Comment by Dragnucs** [comment]
Thank you.

**Comment by woefe** [comment]
A few days ago libxml2 was updated in Fedora. The issue seems to be resolved.

**Comment by Dragnucs** [comment]
Good thing.
